name: New prediction
description: Create new prediction
title: "[PRED] "
body:
  - type: input
    id: author-name
    attributes:
      label: Author Name
    validations:
      required: true

  - type: input
    id: author-id
    attributes:
      label: Author ID
    validations:
      required: false 

  - type: textarea
    id: statement-ru
    attributes:
      label: Statement [ru]
    validations:
      required: true

  - type: textarea
    id: context-ru
    attributes:
      label: Context [ru] 
    validations:
      required: false

  - type: textarea
    id: notes-ru
    attributes:
      label: Notes [ru]
    validations:
      required: true

  - type: textarea
    id: title-ru
    attributes:
      label: HTML Title [ru]
    validations:
      required: true

  - type: textarea
    id: statement-en
    attributes:
      label: Statement [en]
    validations:
      required: true

  - type: textarea
    id: context-en
    attributes:
      label: Context [en]
    validations:
      required: false

  - type: textarea
    id: notes-en
    attributes:
      label: Notes [en]
    validations:
      required: true

  - type: textarea
    id: title-en
    attributes:
      label: HTML Title [en]
    validations:
      required: true

  - type: input
    id: original-language
    attributes:
      label: Original Language
      placeholder: ru
    validations:
      required: true

  - type: input
    id: time-statement
    attributes:
      label: Statement Date
      placeholder: YYYY-MM-DD
    validations:
      required: true

  - type: input
    id: time-awaiting
    attributes:
      label: Due Date
      placeholder: YYYY-MM-DD
    validations:
      required: false

  - type: input
    id: time-verified
    attributes:
      label: Outcome Date
      placeholder: YYYY-MM-DD
    validations:
      required: false


  - type: dropdown
    id: complexity
    attributes:
      label: Complexity
      default: 0
      options:
        - Complex
        - Regular
    validations:
      required: true

  - type: dropdown
    id: confidence
    attributes:
      label: Confidence
      default: 1
      options:
        - Confident
        - Careful
    validations:
      required: true

  - type: dropdown
    id: status
    attributes:
      label: Status
      default: 0
      options:
        - Awaiting
        - Completely
        - Almost
        - Didnot
        - Unverifiable
    validations:
      required: true
