name: New prediction
description: Create new prediction
title: "[NEW-PREDICTION] "
body:
  - type: input
    id: author-id
    attributes:
      label: author-id
      description: Author ID followed by the author's name in free form (examples - 10 Elon Musk, 10 elon-musk, 10 Илон Маск)
      placeholder: 
    validations:
      required: true 

  - type: textarea
    id: statement-ru
    attributes:
      label: statement.ru
      description: Direct quote or translation, without any additional comments. Russian version.
    validations:
      required: true

  - type: textarea
    id: context-ru
    attributes:
      label: context.ru 
      description: Quote context. To clarify the subject matter if it is not fully apparent from the direct quote. Russian version.
    validations:
      required: false

  - type: textarea
    id: notes-ru
    attributes:
      label: notes.ru
      description: Notes and references. Russian version.
    validations:
      required: true

  - type: input
    id: title-ru
    attributes:
      label: title.ru
      description: HTML title. Preferably no more than 100 characters. Russian version.
    validations:
      required: true

  - type: textarea
    id: statement-en
    attributes:
      label: statement.en
      description: English version
    validations:
      required: true

  - type: textarea
    id: context-en
    attributes:
      label: context.en
      description: English version
    validations:
      required: false

  - type: textarea
    id: notes-en
    attributes:
      label: notes.en
      description: English version
    validations:
      required: true

  - type: input
    id: title-en
    attributes:
      label: title.en
      description: English version
    validations:
      required: true

  - type: input
    id: original-language
    attributes:
      label: original-language
      description: Examples - ru, en, de
    validations:
      required: true

  - type: input
    id: time-statement
    attributes:
      label: time-statement
      placeholder: YYYY-MM-DD
    validations:
      required: true

  - type: input
    id: time-awaiting
    attributes:
      label: time-awaiting
      description: Due Date. Leave blank if the Due Date is unknown.
      placeholder: YYYY-MM-DD
    validations:
      required: false

  - type: input
    id: time-verified
    attributes:
      label: time-verified
      description: Outcome Date. Leave blank if the prediction outcome is not yet known. Required if the outcome is known.
      placeholder: YYYY-MM-DD
    validations:
      required: false


  - type: dropdown
    id: complexity
    attributes:
      label: complexity
      default: 0
      options:
        - complex
        - regular
    validations:
      required: true

  - type: dropdown
    id: confidence
    attributes:
      label: confidence
      default: 1
      options:
        - confident
        - careful
    validations:
      required: true

  - type: dropdown
    id: status
    attributes:
      label: status
      default: 0
      options:
        - awaiting
        - completely
        - almost
        - didnot
        - unverifiable
    validations:
      required: true
